### ISSUE TITLE
Getting started doc?

### ISSUE THREAD

**Issue by HParker** [matthiaskramm/cagekeeper#1]
I would like to use cagekeeper, but I don't know how to set it up or use it. Is there any chance you know of examples or blog posts about using it?

It would be great if this information could feed back into a getting started doc on the repo.

Thanks!

**Comment by matthiaskramm** [comment]
As far as I know, fruitbots.org is the only user of this project.

Agreed that a getting-started doc would be great. I'll not have time to
write one anytime soon, though...

**Comment by HParker** [comment]
I would love to help, but could use some direction to get moving. for example, I am not sure of the required packages, or if my platform (osx) is supported. Then if have have successfully built the project, what would I do to run some arbitrary code in a sandbox? I would like to set this up in a rails app to run in a background task.

**Comment by HParker** [comment]
I am also open to looking at other projects if you can recommend another solution. I understand time is a rare resource and I have no right to ask for yours.
